### ISSUE TITLE
JupyterHub

### ISSUE THREAD

**Issue by ghost** [ctic-sje-ifsc/servicos_kubernetes#1]
[JupyterHub](https://jupyterhub.readthedocs.io/en/latest/) como mais um serviço a ser oferecido.

**Comment by souzagaabriel** [comment]
Coloquei no ar e constatei que temos o seguinte problema, no login do usuário é criado um PVC para ele e um POD que utiliza esse PVC. A principio não sabemos (ou talvez não tenha como) alocar vários PVC a um mesmo PV. E como os PV's são criados na mão não seria viável criar um por usuário.

**Comment by souzagaabriel** [comment]
A solução para o JupyterHub na nossa estrutura talvez seja nesse sentido https://github.com/kubernetes-incubator/external-storage/tree/master/nfs, já que ele utiliza StorageClass https://zero-to-jupyterhub.readthedocs.io/en/latest/create-k8s-cluster.html#next-step

**Comment by ghost** [comment]
Esta demanda será fechada por falta de interesse.
