### ISSUE TITLE
Front-end NGINX: analisar uso de Ingress ao invés de Deployment

### ISSUE THREAD

**Issue by ghost** [ctic-sje-ifsc/servicos_kubernetes#10]
Usar NGINX como mais um [serviço](https://github.com/ctic-sje-ifsc/kubernetes/tree/master/srv/nginx) traz o problema de encerrar/iniciar os seus pods toda vez que algum back-end atualiza seu(s) registro(s) DNS, como por exemplo - por isso a existência do [nginx-dev](https://github.com/ctic-sje-ifsc/kubernetes/tree/master/srv/nginx-dev).

O objeto [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) server justamente para isso, mas nos primeiros testes (pré-GitHub) não houve sucesso. Voltemos ao tema, desta vez validando [a configuração](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md) para compatibilizar o atual uso de TLS, HTTP/2, WebSocket e outros.

**Comment by souzagaabriel** [comment]
Sim, concordo, inclusive para ficar compatível com implementações em nuvens públicas. Lembro que tinhas começado um [branche](https://github.com/ctic-sje-ifsc/kubernetes/tree/ingress).

**Comment by souzagaabriel** [comment]
Como iremos atualizar a nuvem para o Tectonic teremos que estudar automaticamente isso. Faremos a migração dos serviços já mudando para Ingress.

**Comment by ghost** [comment]
Issue sem atualização. Desde 65c7e281d525e31dc6938ecc1d650a509f7d15dc o uso de Ingress já existe em caráter de teste.
