### ISSUE TITLE
Nyblab

### ISSUE THREAD

**Issue by ghost** [ctic-sje-ifsc/servicos_kubernetes#3]
Adicionar o [rwnobrega/nyqlab](https://github.com/rwnobrega/nyqlab) como serviço na infraestrutura do câmpus.

**Comment by souzagaabriel** [comment]
Criei um canal no RocketChat para discutirmos sobre esse.

**Comment by souzagaabriel** [comment]
Já está no ar (sem autenticação LDAP ainda) 199bd668364fc8d2cd91c4fb4081ab947d7c53ad

**Comment by souzagaabriel** [comment]
Agora com autenticação LDAP para os servidores do IFSC (Profs e TAE) c91420fb08b9309681e17edade2ae57b8fd2bcb5 e com suporte a X2GO.

**Comment by souzagaabriel** [comment]
Por hora.
