### ISSUE TITLE
Verificar Nextcloud patinando (conf Nginx?)

### ISSUE THREAD

**Issue by souzagaabriel** [ctic-sje-ifsc/servicos_kubernetes#6]

**Comment by ghost** [comment]
Após analisar o tráfego de rede do contêiner principal (`app=nextcloud-nextcloud`), percebeu-se uma demora significativa entre esse e `app=nextcloud-redis` (até 50s para transferência de dados). O cache `redis`, portanto, foi zerado e reiniciado o pod `app=nextcloud-redis`. O serviço, ao que parece, normalizou nesse quesito, mas ainda demanda processamento significativo, o que implica uma pequena, mas sensível demora.

**Comment by souzagaabriel** [comment]
@boidacarapreta Fiz duas implementações 3a12cdc6483786a9350c794b6da73b4145d62d7c :
- Uma nextcloud_fpm https://github.com/nextcloud/docker baseado nesse docker compose.
- e outra nextcloud_wonderfall https://github.com/Wonderfall/dockerfiles/tree/master/nextcloud baseado nesse docker compose.

Já estão criadas as pastas no storage1.

A segunda implementação precisa de um nginx.conf... tentei o que ele sugere https://github.com/nextcloud/docker/tree/master/.examples e também esse https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html mas não foi.

Não consegui deixar redonda funcionando nenhuma das duas.

**Comment by ghost** [comment]
O serviço não é mais oferecido, logo esta tarefa será fechada por não ser mais necessária.
